[project]
name = "airfoil_shape_opt_deep_rl"
version = "0.1.0"
description = "Aerodynamic shape optimization using deep reinforcement learning."
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = []
